# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CPOHScheduler' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'GoogleSignIn', '~> 4.4.0'
  pod 'CalendarSwift', '~> 0.1.8'
  pod 'DayScheduleView', '~> 0.11.0'
  pod 'GTMOAuth2', '~> 1.1.6'
  pod 'AeroGearOAuth2', '~> 2.0.0'
  pod 'OAuthSwift', '~> 1.3.0'
  pod 'CalendarKit', '~> 0.5.1'
  pod 'Firebase/Core'
  pod 'Firebase/Database'

  # Pods for CPOHScheduler

  target 'CPOHSchedulerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CPOHSchedulerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
